Repository 6candoit/Plrecipe, pull requests merged in 2024-02, with the labels that each got.

#51 [UPDATE] placeMapper 조회 테스트
  plrecipe/plrecipe/build.gradle
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/follow/Follow.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/follow/FollowDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/follow/FollowMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/group/Group.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/group/GroupDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/group/GroupMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/member/Member.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/member/MemberDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/member/MemberMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/place/Place.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/place/PlaceDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/place/PlaceMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/post/Post.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/post/PostDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/post/PostMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/common/MyBatisConfig.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/follow/Follow.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/follow/FollowDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/follow/FollowMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/group/Group.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/group/GroupDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/group/GroupMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/member/Member.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/member/MemberDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/member/MemberMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/Place.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/PlaceDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/PlaceMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/Post.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/PostDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/PostMapper.java
  plrecipe/plrecipe/src/main/resources/application.yml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/feature/post/PostMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/follow/FollowMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/group/GroupMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/member/MemberMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/place/PlaceMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/post/PostMapper.xml
  plrecipe/plrecipe/src/test/java/com/sixcandoit/plrecipe/feature/place/PlaceServiceTests.java
Labels: enhancement

#54 [UPDATE] place add findStarByPlace/findPlaceByCategory
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/Place.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/PlaceMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/PlaceStarDTO.java
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/place/PlaceMapper.xml
  plrecipe/plrecipe/src/test/java/com/sixcandoit/plrecipe/feature/place/PlaceServiceTests.java
Labels: enhancement

#59 [MODIFY] modify mapper
  plrecipe/.idea/workspace.xml
  plrecipe/plrecipe/src/main/java/com/sixcandoit/feature/member/MemberGrade.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/group/Group.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/group/GroupMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/Course.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/CourseMapper.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/Place.java
  plrecipe/plrecipe/src/main/resources/application.yml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/group/GroupMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/place/CourseMapper.xml
  plrecipe/plrecipe/src/test/java/com/sixcandoit/plrecipe/feature/group/GroupServiceTests.java
  plrecipe/plrecipe/src/test/java/com/sixcandoit/plrecipe/feature/place/CoursePlaceServiceTests.java
Labels: bug

#60 Post to Develop
  plrecipe/plrecipe/src/main/java/com/sixcandoit/configuration/PlrecipeConfiguration.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/place/Place.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/HashTagDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/MemberCount.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/Post.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/PostDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/PostHashtagDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/PostLikeDTO.java
  plrecipe/plrecipe/src/main/java/com/sixcandoit/plrecipe/feature/post/PostMapper.java
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/member/MemberMapper.xml
  plrecipe/plrecipe/src/main/resources/com/sixcandoit/plrecipe/feature/post/PostMapper.xml
  plrecipe/plrecipe/src/test/java/com/sixcandoit/plrecipe/feature/post/PostServiceTests.java
Labels: bug, enhancement
